### PR TITLE
Lane dev

### PR DESCRIPTION
**Pull request by DrDillicious**
Added css and created a parragraph

### CODE REVIEW

**Comment by smaccoun** [comment]
Okay, good job Lane! You are now a github pro!

**Comment by DrDillicious** [comment]
That's nice of you to say but I feel I still have much to learn!

**Comment by smaccoun** [comment]
With the right guidance and attitude you can do it!

**Comment by DrDillicious** [comment]
dog-breath
REMEMBER TO BRUSH YOUR TEETH!

**Pull request merged**
